import * as vscode from "vscode";

const quickStartContent = [
  "# TCalc Quick Start",
  "",
  "A step-by-step guide to using Workspace Model Advisor.",
  "",
  "---",
  "",
  "## Step 1: Scan Workspace",
  "",
  "Run `TCalc: Scan Workspace` to analyze your current project.",
  "",
  "This will:",
  "- Walk all files in your workspace",
  "- Estimate token usage per file and folder",
  "- Count files by category (code, config, docs, etc.)",
  "- Report the total estimated token count",
  "",
  "---",
  "",
  "## Step 2: Set a Goal",
  "",
  "Run `TCalc: Set Workspace Goal` to tell TCalc what you are working on.",
  "",
  "Available goals:",
  "- `build-mvp` \u2014 Building a minimum viable product",
  "- `add-feature` \u2014 Adding a feature to existing code",
  "- `debug` \u2014 Debugging an issue",
  "- `refactor` \u2014 Refactoring code",
  "- `migration` \u2014 Migrating between frameworks or versions",
  "- `security-review` \u2014 Reviewing code for vulnerabilities",
  "- `test-generation` \u2014 Writing tests",
  "- `documentation` \u2014 Writing docs",
  "- `architecture-planning` \u2014 Planning architecture",
  "- `cleanup` \u2014 General cleanup",
  "",
  "Your goal influences which models are recommended.",
  "",
  "---",
  "",
  "## Step 3: Compare Models",
  "",
  "Run `TCalc: Compare Models` to see which AI models fit your workspace.",
  "",
  "The comparison shows:",
  "- Model name and provider",
  "- Context window size vs your workspace tokens",
  "- Estimated cost per session",
  "- Suitability for your selected goal",
  "- Privacy mode (local-first vs cloud-ok)",
  "",
  "---",
  "",
  "## Step 4: Generate a Repo Map",
  "",
  "Run `TCalc: Generate Repo Map` to create a structured map of your codebase.",
  "",
  "Repo maps are useful for:",
  "- Providing context to coding agents (Claude Code, Cursor, etc.)",
  "- Understanding high-level project structure",
  "- Identifying key files and directories",
  "",
  "You can set a token budget to control how detailed the map is.",
  "",
  "---",
  "",
  "## Step 5: Generate Agent Rules",
  "",
  "Run `TCalc: Generate Agent Rules` to create configuration files for",
  "AI coding agents based on your workspace structure.",
  "",
  "Supported targets:",
  "- `.clinerules` (Claude Code)",
  "- `.cursor/rules/` (Cursor)",
  "- Generic markdown",
  "",
  "---",
  "",
  "## Step 6: Export a Report",
  "",
  "Run `TCalc: Export Report` to save your analysis as a Markdown or HTML file.",
  "",
  "Reports include:",
  "- Workspace summary with token counts",
  "- Model comparison table",
  "- Repo map (if generated)",
  "- Agent rules (if generated)",
  "- Key recommendations",
  "",
  "---",
  "",
  "## Privacy & Security",
  "",
  "- **Local-first**: all computation runs on your machine",
  "- **No telemetry**: nothing is tracked or sent",
  "- **No cloud calls**: no external network requests from app code",
  "- **Repo maps are structural**: full file bodies are never exposed",
  "",
  "## Resources",
  "",
  "- [GitHub Repository](https://github.com/Sandesh13fr/TCalc)",
  "- [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=Sandesh13fr.tcalc)",
  "- [Open VSX](https://open-vsx.org/extension/Sandesh13fr/tcalc)",
  "- [Documentation](https://github.com/Sandesh13fr/TCalc#readme)",
  "",
  "---",
  "",
  "_TCalc v0.1.2 \u2014 MIT License_",
].join("\n");

export function registerQuickStartCommand(): vscode.Disposable {
  return vscode.commands.registerCommand("workspaceModelAdvisor.quickStart", async () => {
    const doc = await vscode.workspace.openTextDocument({
      content: quickStartContent,
      language: "markdown",
    });
    await vscode.window.showTextDocument(doc, { preserveFocus: true, viewColumn: vscode.ViewColumn.Active });
  });
}
