packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@vscode/vsce-sign': true
  keytar: true
  sharp: true
  tree-sitter: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-typescript: true
