# TCalc JetBrains Plugin
pluginGroup = com.tcalc.plugin
pluginName = TCalc
pluginVersion = 0.1.4
pluginSinceBuild = 242
pluginUntilBuild = 243.*

platformType = IC
platformVersion = 2024.3
platformDownloadSources = false

# Kotlin
kotlin.stdlib.default.dependency = false

# Gradle
org.gradle.jvmargs = -Xmx2048m -Dfile.encoding=UTF-8
