import type { OptimizationMode, AgentRulesOutput } from "@wma/core";

export interface WindsurfRulesOptions {
  mode?: OptimizationMode;
  workspaceTokens?: number;
  modelRecommendations?: string[];
  testCommand?: string;
  buildCommand?: string;
}

export function generateWindsurfRules(options: WindsurfRulesOptions = {}): AgentRulesOutput {
  const mode = options.mode ?? "balanced";
  const tokens = options.workspaceTokens ?? 0;
  const testCmd = options.testCommand ?? "pnpm test";
  const buildCmd = options.buildCommand ?? "pnpm build";

  const avoidPatterns = [
    "dist/",
    "node_modules/",
    ".git/",
    "*.min.js",
    "*.bundle.js",
    "*.lock",
    "*.log",
    "coverage/",
  ];

  const lines: string[] = [
    `# Windsurf Workspace Rules (.windsurfrules)`,
    `# Generated by TCalc (Local Workspace Token Calculator & Optimizer)`,
    ``,
    `## Workspace Context & Token Budget`,
    `- Estimated Workspace Size: ~${tokens.toLocaleString("en-US")} tokens`,
    `- Optimization Mode: ${mode}`,
  ];

  if (options.modelRecommendations && options.modelRecommendations.length > 0) {
    lines.push(`- Recommended Models: ${options.modelRecommendations.join(", ")}`);
  }

  lines.push(
    ``,
    `## Cascade Agent Execution Guidelines`,
    `- Read workspace architecture before making invasive modifications.`,
    `- Use focused edits; prefer targeted replacements over full-file rewrites.`,
    `- Never modify or regenerate files matching ignore patterns below.`,
    `- Maintain existing code style, documentation comments, and typing annotations.`,
    ``,
    `## Verification & Quality Gates`,
    `- Build Command: \`${buildCmd}\``,
    `- Test Command: \`${testCmd}\``,
    `- Run tests after every discrete component change to verify no regression.`,
    ``,
    `## File Exclusion Boundaries`,
  );

  for (const pattern of avoidPatterns) {
    lines.push(`- Avoid reading/indexing: \`${pattern}\``);
  }

  lines.push(
    ``,
    `## Behavioral Mode Instructions`,
  );

  switch (mode) {
    case "concise":
      lines.push(
        `- Be extremely direct. State the change and rationale in 2-3 sentences.`,
        `- Omit conversational filler, disclaimers, and pleasantries.`,
      );
      break;
    case "patch-only":
      lines.push(
        `- Output only unified diffs or minimal code replacement chunks.`,
        `- Zero conversational explanations unless specifically requested.`,
      );
      break;
    case "caveman":
      lines.push(
        `- Terse bullet points only. Maximum brevity.`,
      );
      break;
    default:
      lines.push(
        `- Provide balanced explanations with clear code snippets and verification notes.`,
      );
  }

  lines.push("");

  const content = lines.join("\n");

  return {
    target: "generic" as any,
    fileName: ".windsurfrules",
    content,
    mode,
    estimatedTokens: Math.ceil(content.length / 4),
    rulesCount: 6,
    avoidFiles: avoidPatterns,
  };
}
