import type {
  AgentTarget,
  OptimizationMode,
  AgentRulesOutput,
} from "@wma/core";

export interface GenerateAgentRulesOptions {
  target: AgentTarget;
  mode: OptimizationMode;
  workspaceTokens?: number;
  modelRecommendations?: string[];
}

function getFileName(target: AgentTarget): string {
  switch (target) {
    case "cursor":
      return ".cursorrules";
    case "claude-code":
      return "CLAUDE.md";
    case "codex":
      return ".codexrules";
    case "cline":
      return ".clinerules";
    case "roo":
      return ".roorules";
    case "continue":
      return ".continuerules";
    case "aider":
      return ".aiderrules";
    case "generic":
      return "AGENTS.md";
  }
}

function getTokenBudget(mode: OptimizationMode): number {
  switch (mode) {
    case "concise":
      return 16000;
    case "patch-only":
      return 32000;
    case "caveman":
      return 8000;
    default:
      return 64000;
  }
}

function getAvoidFiles(mode: OptimizationMode): string[] {
  switch (mode) {
    case "repo-map-first":
      return ["dist/", "node_modules/", ".git/", "*.min.js", "*.bundle.js"];
    case "patch-only":
      return ["*.lock", "*.log", "dist/", ".env*"];
    default:
      return ["node_modules/", ".git/", "dist/"];
  }
}

function buildRulesContent(
  target: AgentTarget,
  mode: OptimizationMode,
  workspaceTokens: number,
  modelRecommendations: string[],
): string {
  const sections: string[] = [];

  sections.push(`# ${target} Agent Rules`);
  sections.push(`> Generated by @wma/agent-rules`);
  sections.push(`> Mode: ${mode}`);
  sections.push("");

  sections.push(`## Workspace Context`);
  sections.push(`- Estimated workspace tokens: ${workspaceTokens.toLocaleString()}`);
  if (modelRecommendations.length > 0) {
    sections.push(`- Recommended models: ${modelRecommendations.join(", ")}`);
  }
  sections.push("");

  sections.push(`## Behavior`);
  switch (mode) {
    case "normal":
      sections.push(`- Read and edit files with full context awareness.`);
      sections.push(`- Apply changes incrementally and verify before continuing.`);
      sections.push(`- Respect existing code style, naming conventions, and architecture.`);
      sections.push(`- Ask for clarification when requirements are ambiguous.`);
      break;
    case "concise":
      sections.push(`- Minimize output. Do not include plans or reasoning unless asked.`);
      sections.push(`- Prefer single-line edits over multi-line rewrites.`);
      sections.push(`- Omit explanatory commentary. Just produce the code change.`);
      sections.push(`- Use short variable names when appropriate to reduce token use.`);
      break;
    case "caveman":
      sections.push(`- Use short, simple words and sentences.`);
      sections.push(`- Avoid abstractions, interfaces, or complex patterns.`);
      sections.push(`- Prefer copy-paste reuse over extraction.`);
      sections.push(`- Do not add type annotations or generics unless necessary.`);
      break;
    case "patch-only":
      sections.push(`- Only output file edits in patch format.`);
      sections.push(`- Do not echo back the user's code or describe what you changed.`);
      sections.push(`- Skip any conversational preamble or sign-off.`);
      sections.push(`- Use unified diff or search/replace blocks exclusively.`);
      break;
    case "test-first":
      sections.push(`- Before implementing any function, write its test first.`);
      sections.push(`- Cover edge cases, error states, and happy paths.`);
      sections.push(`- Run the test suite after every change.`);
      sections.push(`- Do not skip tests for "simple" changes.`);
      break;
    case "plan-then-edit":
      sections.push(`- Before editing, output a one-paragraph plan with the files to touch.`);
      sections.push(`- Wait for user confirmation before making edits.`);
      sections.push(`- After edits, summarize what changed and why.`);
      break;
    case "repo-map-first":
      sections.push(`- Start by reading the repository map (file tree + file summaries).`);
      sections.push(`- Do not read full file contents unless required for the edit.`);
      sections.push(`- Use directory listings to find relevant files before reading them.`);
      sections.push(`- Prefer targeted reads over scanning entire directories.`);
      break;
    case "ask-before-large-files":
      sections.push(`- Before reading files >5 KB, ask the user for permission.`);
      sections.push(`- Use file summaries and head/tail reads to minimize token usage.`);
      sections.push(`- Cache previously read file contents within the session.`);
      sections.push(`- Do not read large binary files or lock files.`);
      break;
    case "no-full-file-dumps":
      sections.push(`- Never output the full content of an unmodified file.`);
      sections.push(`- Use search/replace blocks to show only changed regions.`);
      sections.push(`- When reviewing, reference line numbers rather than dumping code.`);
      break;
    case "use-summaries":
      sections.push(`- When exploring the codebase, request summaries over full file reads.`);
      sections.push(`- Build a mental model of the codebase using tree views and grep.`);
      sections.push(`- Use file-at-a-time access rather than batch reads.`);
      break;
  }
  sections.push("");

  sections.push(`## File Handling`);
  for (const pattern of getAvoidFiles(mode)) {
    sections.push(`- Avoid reading or editing: \`${pattern}\``);
  }
  sections.push("");

  sections.push(`## Token Budget`);
  sections.push(`- Target token limit: ${getTokenBudget(mode).toLocaleString()} tokens`);
  sections.push("");

  sections.push(`## Rules`);
  sections.push(`1. Stay within the token budget for every response.`);
  sections.push(`2. Do not modify files outside the workspace root.`);
  sections.push(`3. Respect .gitignore patterns when exploring the file tree.`);
  sections.push(`4. Confirm before running destructive commands (delete, force-push, etc.).`);
  sections.push(`5. When in doubt, ask the user — do not guess.`);

  return sections.join("\n");
}

export function generateAgentRules(
  options: GenerateAgentRulesOptions,
): AgentRulesOutput {
  const { target, mode, workspaceTokens = 0, modelRecommendations = [] } = options;

  const fileName = getFileName(target);
  const content = buildRulesContent(target, mode, workspaceTokens, modelRecommendations);

  return {
    target,
    mode,
    fileName,
    content,
    avoidFiles: getAvoidFiles(mode),
    tokenBudget: getTokenBudget(mode),
  };
}
