import type { OptimizationMode, AgentRulesOutput } from "@wma/core";

export interface CopilotInstructionsOptions {
  mode?: OptimizationMode;
  workspaceTokens?: number;
  projectDescription?: string;
  codingConventions?: string[];
}

export function generateCopilotInstructions(
  options: CopilotInstructionsOptions = {},
): AgentRulesOutput {
  const mode = options.mode ?? "balanced";
  const tokens = options.workspaceTokens ?? 0;
  const description = options.projectDescription ?? "Local-first token and context optimization workspace";

  const avoidPatterns = [
    "node_modules/",
    ".git/",
    "dist/",
    "build/",
    "*.min.js",
    "*.bundle.js",
    "coverage/",
  ];

  const lines: string[] = [
    `# GitHub Copilot Instructions (.github/copilot-instructions.md)`,
    `# Generated by TCalc (Local Workspace Token Calculator & Optimizer)`,
    ``,
    `## Project Overview`,
    `- Description: ${description}`,
    `- Workspace Token Budget: ~${tokens.toLocaleString("en-US")} tokens`,
    `- Optimization Preference: ${mode}`,
    ``,
    `## Coding Conventions & Style`,
    `- Language: TypeScript strict mode enabled throughout.`,
    `- Modularity: Functional programming preferred over deep class inheritance.`,
    `- Documentation: Preserve existing TSDoc/JSDoc comments on unchanged code.`,
    `- Safety: Zero telemetry, zero external network calls in core packages.`,
  ];

  if (options.codingConventions && options.codingConventions.length > 0) {
    for (const conv of options.codingConventions) {
      lines.push(`- ${conv}`);
    }
  }

  lines.push(
    ``,
    `## Pull Request Readiness`,
    `- Always verify code with unit tests before declaring completion.`,
    `- Ensure changes have zero merge conflicts against upstream branches.`,
    `- Avoid introducing new external dependencies without explicit approval.`,
    ``,
    `## Context Guardrails & Excluded Artifacts`,
  );

  for (const p of avoidPatterns) {
    lines.push(`- Exclude from suggestions: \`${p}\``);
  }

  lines.push("");

  const content = lines.join("\n");

  return {
    target: "generic" as any,
    fileName: ".github/copilot-instructions.md",
    content,
    mode,
    estimatedTokens: Math.ceil(content.length / 4),
    rulesCount: 5,
    avoidFiles: avoidPatterns,
  };
}
