import type { OptimizationMode, AgentRulesOutput } from "@wma/core";

export interface GeminiRulesOptions {
  mode?: OptimizationMode;
  workspaceTokens?: number;
  systemRole?: string;
  toolingNotes?: string[];
}

export function generateGeminiRules(options: GeminiRulesOptions = {}): AgentRulesOutput {
  const mode = options.mode ?? "balanced";
  const tokens = options.workspaceTokens ?? 0;
  const systemRole = options.systemRole ?? "Senior Full-Stack Architect & Optimization Specialist";

  const avoidPatterns = [
    ".git/",
    "node_modules/",
    "dist/",
    "build/",
    "*.min.js",
    "*.lock",
    "*.log",
    "*.tmp",
  ];

  const lines: string[] = [
    `# Gemini System Prompt & Guidelines (GEMINI.md)`,
    `# Generated by TCalc (Local Workspace Token Calculator & Optimizer)`,
    ``,
    `## Persona & Role`,
    `- Role: ${systemRole}`,
    `- Workspace Token Footprint: ~${tokens.toLocaleString("en-US")} tokens`,
    `- Mode: ${mode}`,
    ``,
    `## Reasoning & Planning Policy`,
    `- For complex multi-file refactoring, enter Planning Mode and create an implementation plan before edits.`,
    `- Verify code behavior using unit tests before concluding tasks.`,
    `- Strictly preserve documentation integrity and comment headers.`,
    ``,
    `## Tooling & Execution Directives`,
  ];

  if (options.toolingNotes && options.toolingNotes.length > 0) {
    for (const note of options.toolingNotes) {
      lines.push(`- ${note}`);
    }
  } else {
    lines.push(
      `- Prefer precise file replacement chunks over full-file overwrites.`,
      `- Do not run destructive git commands or commit directly without verification.`,
    );
  }

  lines.push(
    ``,
    `## Token Boundaries & Excluded Paths`,
  );

  for (const p of avoidPatterns) {
    lines.push(`- Ignore from workspace search: \`${p}\``);
  }

  lines.push("");

  const content = lines.join("\n");

  return {
    target: "generic" as any,
    fileName: "GEMINI.md",
    content,
    mode,
    estimatedTokens: Math.ceil(content.length / 4),
    rulesCount: 5,
    avoidFiles: avoidPatterns,
  };
}
