"use client";

import { useEffect, useRef, useState } from "react";

type ModelPick = { displayName?: string; modelId?: string; provider?: string; tier?: string; score?: number | { totalScore?: number } };
type TCalcReport = {
  schemaVersion: "1.0.0";
  title: string;
  generatedAt?: string;
  goal?: string | null;
  summary: { totalFiles: number; includedFiles: number; excludedFiles: number; totalEstimatedTokens: number; includedTokens: number };
  recommendations?: { cheapestSufficient?: ModelPick; balanced?: ModelPick; highConfidence?: ModelPick } | null;
};
type SavedReport = Pick<TCalcReport, "title" | "goal" | "generatedAt" | "summary"> & { id: string };

const exampleReport: TCalcReport = {
  schemaVersion: "1.0.0",
  title: "commerce-platform",
  generatedAt: "2026-07-20T12:00:00.000Z",
  goal: "add-feature",
  summary: { totalFiles: 742, includedFiles: 612, excludedFiles: 130, totalEstimatedTokens: 221430, includedTokens: 184760 },
  recommendations: {
    cheapestSufficient: { displayName: "DeepSeek V3", provider: "DeepSeek", score: 0.86 },
    balanced: { displayName: "Gemini 2.5 Pro", provider: "Google AI", score: 0.91 },
    highConfidence: { displayName: "Claude Sonnet 4", provider: "Anthropic", score: 0.89 },
  },
};

function isReport(value: unknown): value is TCalcReport {
  if (!value || typeof value !== "object") return false;
  const report = value as Partial<TCalcReport>;
  const summary = report.summary;
  return report.schemaVersion === "1.0.0" && typeof report.title === "string" && !!summary &&
    ["totalFiles", "includedFiles", "excludedFiles", "totalEstimatedTokens", "includedTokens"]
      .every((key) => Number.isFinite(summary[key as keyof typeof summary]) && summary[key as keyof typeof summary] >= 0);
}

function score(model: ModelPick) {
  const value = typeof model.score === "number" ? model.score : model.score?.totalScore;
  return Number.isFinite(value) ? `${Math.round((value as number) * 100)}/100` : "—";
}

export default function ReportViewer() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [report, setReport] = useState<TCalcReport>(exampleReport);
  const [status, setStatus] = useState("Showing a safe example report.");
  const [error, setError] = useState("");
  const [savedReports, setSavedReports] = useState<SavedReport[]>([]);

  useEffect(() => {
    fetch("/api/reports")
      .then((response) => response.ok ? response.json() : Promise.reject())
      .then((items) => { if (Array.isArray(items)) setSavedReports(items); })
      .catch(() => undefined);
  }, []);

  const openReport = (value: unknown, message: string) => {
    if (!isReport(value)) throw new Error("This is not a valid TCalc report (schema 1.0.0). ");
    setReport(value);
    setStatus(message);
    setError("");
  };

  const onFile = async (file?: File) => {
    if (!file) return;
    try {
      if (file.size > 1_000_000) throw new Error("Report is larger than the 1 MB limit.");
      openReport(JSON.parse(await file.text()), `Opened ${file.name} locally. Nothing was uploaded.`);
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : String(caught));
      setStatus("Could not open that report.");
    } finally {
      if (inputRef.current) inputRef.current.value = "";
    }
  };

  const picks = [
    ["Cheapest sufficient", report.recommendations?.cheapestSufficient],
    ["Balanced", report.recommendations?.balanced],
    ["High confidence", report.recommendations?.highConfidence],
  ] as const;

  return (
    <div className="report-layout">
      <div className="section-copy">
        <p className="eyebrow"><span />Local report viewer</p>
        <h2>Open the evidence.<br />Keep it in your browser.</h2>
        <p>Select a JSON report generated by TCalc. It is parsed on this page and is never uploaded to the hosted site.</p>
        <div className="button-row">
          <label className="button" htmlFor="report-file">Open JSON report</label>
          <input ref={inputRef} id="report-file" className="visually-hidden" type="file" accept="application/json,.json" onChange={(event) => void onFile(event.target.files?.[0])} />
          <button className="text-button" type="button" onClick={() => openReport(exampleReport, "Showing a safe example report.")}>Load example</button>
        </div>
        <p className="status" role="status">{status}</p>
      </div>
      <article className="report-card" aria-live="polite">
        {error ? <p className="report-error">{error}</p> : <>
          <header><small>{report.goal ?? "No goal"} · {report.generatedAt ? new Date(report.generatedAt).toLocaleDateString() : "Unknown date"}</small><h3>{report.title}</h3></header>
          <div className="report-metrics">
            <span><small>Included tokens</small><strong>{report.summary.includedTokens.toLocaleString()}</strong></span>
            <span><small>Files scanned</small><strong>{report.summary.totalFiles.toLocaleString()}</strong></span>
            <span><small>Files excluded</small><strong>{report.summary.excludedFiles.toLocaleString()}</strong></span>
          </div>
          <ol className="report-picks">
            {picks.map(([label, model], index) => model ? (
              <li key={label}><span className="rank">0{index + 1}</span><div><strong>{model.displayName ?? model.modelId ?? "Unknown model"}</strong><small>{label} · {model.provider ?? model.tier ?? "Catalog provider"}</small></div><b>{score(model)}</b></li>
            ) : null)}
          </ol>
        </>}
      </article>
      {savedReports.length > 0 && <section className="saved-reports"><h3>Saved team reports</h3>{savedReports.map((saved) => <button key={saved.id} type="button" onClick={async () => {
        try {
          const response = await fetch(`/api/reports/${encodeURIComponent(saved.id)}`);
          if (!response.ok) throw new Error("Could not load that saved report.");
          openReport(await response.json(), `Opened saved report ${saved.title}.`);
        } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); }
      }}>{saved.title} · {saved.summary.includedTokens.toLocaleString()} tokens</button>)}</section>}
    </div>
  );
}
